DROP TABLE IF EXISTS tweets CASCADE;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_name TEXT NOT NULL 
);

CREATE TABLE tweets (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tweet TEXT NOT NULL,
    linked_user BIGINT REFERENCES users(id) ON DELETE SET NULL
);
